### ISSUE TITLE
Custom JARs in /var/mqsi/shared-classes

### ISSUE THREAD

**Issue by radekg** [ot4i/ace-docker#138]
I'm trying to configure AMQP connection using the `org.apache.activemq.jndi.ActiveMQInitialContextFactory` initial context factory. All the documentation I can find talks about deploying the `activemq-all -<version>.jar` and `jndi.properties` file into the `/var/mqsi/shared-classes` directory and restarting the broker.

I have the following bit in my compose file:

```yaml
    ace-mq:
        image: ace-dev-mq-dev:latest
        restart: unless-stopped
        environment:
            - LICENSE=accept
            - ACE_SERVER_NAME=ace-to-qpid
            - MQ_QMGR_NAME=QMGR
        volumes:
            - ./assets/activemq-all-5.16.0.jar:/var/mqsi/shared-classes/activemq-all-5.16.0.jar:rw
            - ./assets/qpid-jndi.properties:/var/mqsi/shared-classes/jndi.properties:rw
        ports:
            - 1414:1414
            - 7600:7600
            - 7800:7800
            - 7843:7843
        networks:
            - ace
```

After starting my compose setup, I execute this command in the shell:

```
$ docker exec 9fe23221a71b ls -la /var/mqsi/shared-classes
total 18992
drwxrwxr-x 1 root mqbrkrs     4096 Sep 30 13:49 .
drwxrwxr-x 1 root mqbrkrs     4096 Sep 30 13:47 ..
-rw-r--r-- 1 mqm  mqm     18608958 Sep 29 12:15 activemq-all-5.16.0.jar
-rw-r--r-- 1 mqm  mqm          666 Sep 30 13:52 jndi.properties
```

But when I deploy my bar file, I get the following error:

```
ace-mq_1           | 2020-09-30 14:08:38.933     41 javax.naming.NoInitialContextException: Cannot instantiate class: org.apache.activemq.jndi.ActiveMQInitialContextFactory [Root exception is java.lang.ClassNotFoundException: org.apache.activemq.jndi.ActiveMQInitialContextFactory]
ace-mq_1           | 2020-09-30 14:08:38.936     41 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:685)
ace-mq_1           | 2020-09-30 14:08:38.937     41 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:324)
ace-mq_1           | 2020-09-30 14:08:38.938     41 	at javax.naming.InitialContext.init(InitialContext.java:255)
ace-mq_1           | 2020-09-30 14:08:38.939     41 	at javax.naming.InitialContext.<init>(InitialContext.java:227)
ace-mq_1           | 2020-09-30 14:08:38.940     41 	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:112)
ace-mq_1           | 2020-09-30 14:08:38.942     41 	at com.ibm.broker.jmsclienthelper.JMSClientHelper.setInitialContext(JMSClientHelper.java:817)
ace-mq_1           | 2020-09-30 14:08:38.944     41 	at com.ibm.broker.jmsclienthelper.JMSClientInputReplyHelper.getJMSInput(JMSClientInputReplyHelper.java:309)
ace-mq_1           | 2020-09-30 14:08:38.946     41 	at com.ibm.broker.jmsclientnodes.JMSClientInputNode.run(JMSClientInputNode.java:438)
ace-mq_1           | 2020-09-30 14:08:38.948     41 Caused by: java.lang.ClassNotFoundException: org.apache.activemq.jndi.ActiveMQInitialContextFactory
ace-mq_1           | 2020-09-30 14:08:38.949     41 	at java.lang.Class.forNameImpl(Native Method)
ace-mq_1           | 2020-09-30 14:08:38.951     41 	at java.lang.Class.forName(Class.java:420)
ace-mq_1           | 2020-09-30 14:08:38.952     41 	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:103)
ace-mq_1           | 2020-09-30 14:08:38.953     41 	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:73)
ace-mq_1           | 2020-09-30 14:08:38.954     41 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:683)
ace-mq_1           | 2020-09-30 14:08:38.955     41 	... 7 more
ace-mq_1           | 2020-09-30 14:08:41.213184: ACE JMSClient. 'Broker 'integration_server'; Execution Group 'ace-to-qpid'; Message Flow 'amqptestflow'; Node 'JMS Input::ComIbmJMSClientInputNode' ' There is a configuration problem with the JNDI Administered objects where:  Initial Context Factory  = 'org.apache.activemq.jndi.ActiveMQInitialContextFactory'.  Location of the bindings = 'tcp://host:port'.  ConnectionFactory Name   = 'queueConnectionFactory'.  JMS destination  = 'MQSIInputQueue'.  The exception text is : ' Cannot instantiate class: org.apache.activemq.jndi.ActiveMQInitialContextFactory, Failure to obtain JNDI administered objects'.
```

where the root of the problem appears to be: `[Root exception is java.lang.ClassNotFoundException: org.apache.activemq.jndi.ActiveMQInitialContextFactory]`.

Am I doing something wrong or is the `/var/mqsi/shared-classes` directory not used by this Docker image setup?

**Update**

Okay, I managed to establish that the directory is not in the default `lilPath`. I have updated my compose yaml to this:

```
    ace-mq:
        image: ace-dev-mq-dev:latest
        restart: unless-stopped
        environment:
            - LICENSE=accept
            - ACE_SERVER_NAME=ace-to-qpid
            - MQ_QMGR_NAME=QMGR
        volumes:
            - ./assets/server.conf.yaml:/home/aceuser/ace-server/server.conf.yaml:rw
            - ./assets/qpid-jndi.properties:/var/mqsi/shared-classes/jndi.properties:rw
            - ./assets/activemq-client-5.16.0.jar:/var/mqsi/shared-classes/activemq-client-5.16.0.jar:rw
            - ./assets/geronimo-j2ee-management_1.1_spec-1.0.1.jar:/var/mqsi/shared-classes/geronimo-j2ee-management_1.1_spec-1.0.1.jar:rw
            - ./assets/geronimo-jms_1.1_spec-1.1.1.jar:/var/mqsi/shared-classes/geronimo-jms_1.1_spec-1.1.1.jar:rw
            - ./assets/hawtbuf-1.11.jar:/var/mqsi/shared-classes/hawtbuf-1.11.jar:rw
            - ./assets/jmdns-3.4.1.jar:/var/mqsi/shared-classes/jmdns-3.4.1.jar:rw
            - ./assets/javax.ejb-api-3.2.jar:/var/mqsi/shared-classes/javax.ejb-api-3.2.jar:rw
        ports:
            - 1414:1414
            - 7600:7600
            - 7800:7800
            - 7843:7843
        networks:
            - ace
```

Where my `server.conf.yaml` now contains:

```
---
# ACE Integration Server configuration file
...
serverConfVersion: 1

lilPath: '/var/mqsi/shared-classes' 
...
```

And they are now loaded(?) / available(?). But the outcome is the same after deploying the bar file:

```
ace-mq_1           | 2020-09-30 15:11:48.674956: About to 'Initialize' the deployed resource 'test-amqp' of type 'Application'.
ace-mq_1           | 2020-09-30 15:11:49.237000: About to 'Start' the deployed resource 'test-amqp' of type 'Application'.
ace-mq_1           | 2020-09-30 15:11:49.239196: Deployed resource 'amqptestflow' (uuid='amqptestflow',type='MessageFlow') started successfully.
ace-mq_1           | 2020-09-30 15:11:49.240416: Application 'test-amqp' has been created successfully.
ace-mq_1           | 2020-09-30 15:11:49.241116: The source 'rest-deploy.bar' has been successfully deployed.
ace-mq_1           | 2020-09-30 15:11:49.241936: Integration server finished with Configuration message.
ace-mq_1           | 2020-09-30 15:11:50.279     47 javax.naming.NoInitialContextException: Cannot instantiate class: org.apache.activemq.jndi.ActiveMQInitialContextFactory [Root exception is java.lang.ClassNotFoundException: org.apache.activemq.jndi.ActiveMQInitialContextFactory]
ace-mq_1           | 2020-09-30 15:11:50.286     47 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:685)
ace-mq_1           | 2020-09-30 15:11:50.287     47 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:324)
ace-mq_1           | 2020-09-30 15:11:50.289     47 	at javax.naming.InitialContext.init(InitialContext.java:255)
ace-mq_1           | 2020-09-30 15:11:50.290     47 	at javax.naming.InitialContext.<init>(InitialContext.java:227)
ace-mq_1           | 2020-09-30 15:11:50.292     47 	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:112)
ace-mq_1           | 2020-09-30 15:11:50.293     47 	at com.ibm.broker.jmsclienthelper.JMSClientHelper.setInitialContext(JMSClientHelper.java:817)
ace-mq_1           | 2020-09-30 15:11:50.295     47 	at com.ibm.broker.jmsclienthelper.JMSClientInputReplyHelper.getJMSInput(JMSClientInputReplyHelper.java:309)
ace-mq_1           | 2020-09-30 15:11:50.296     47 	at com.ibm.broker.jmsclientnodes.JMSClientInputNode.run(JMSClientInputNode.java:438)
ace-mq_1           | 2020-09-30 15:11:50.297     47 Caused by: java.lang.ClassNotFoundException: org.apache.activemq.jndi.ActiveMQInitialContextFactory
ace-mq_1           | 2020-09-30 15:11:50.299     47 	at java.lang.Class.forNameImpl(Native Method)
ace-mq_1           | 2020-09-30 15:11:50.300     47 	at java.lang.Class.forName(Class.java:420)
ace-mq_1           | 2020-09-30 15:11:50.301     47 	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:103)
ace-mq_1           | 2020-09-30 15:11:50.303     47 	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:73)
ace-mq_1           | 2020-09-30 15:11:50.304     47 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:683)
ace-mq_1           | 2020-09-30 15:11:50.306     47 	... 7 more
ace-mq_1           | 2020-09-30 15:11:52.680196: ACE JMSClient. 'Broker 'integration_server'; Execution Group 'ace-to-qpid'; Message Flow 'amqptestflow'; Node 'JMS Input::ComIbmJMSClientInputNode' ' There is a configuration problem with the JNDI Administered objects where:  Initial Context Factory  = 'org.apache.activemq.jndi.ActiveMQInitialContextFactory'.  Location of the bindings = 'tcp://host:port'.  ConnectionFactory Name   = 'queueConnectionFactory'.  JMS destination  = 'MQSIInputQueue'.  The exception text is : ' Cannot instantiate class: org.apache.activemq.jndi.ActiveMQInitialContextFactory, Failure to obtain JNDI administered objects'.
```

Thank you.
